In [1]:
import numpy as np

In [2]:
temp=np.random.randint(18,40,168)
re_shape=np.reshape(temp,(7,24))


In [3]:
avg_day=np.mean(re_shape,axis=1)
max_day=np.max(re_shape,axis=1)
min_day=np.min(re_shape,axis=1)
hot_hour=temp[temp>35]
average=np.average(temp)
min=np.min(temp)
max=np.max(temp)


In [4]:

print("------weekly temperature analyzer------ \n")
print()
print("__temperature of each day__ \n")
print(re_shape)
print()
for i in range(7):
   print("average temp in day ",i+1," : ",avg_day[i])
   print("max temp in day ",i+1," : ",max_day[i])
   print("min temp in day ",i+1," : ",min_day[i])
print()
print("hot hour : ",hot_hour)
print()
print("average temp in week : ",average)
print()
print("min temp in week : ",min)
print()
print("max temp in week  : ",max)


------weekly temperature analyzer------ 


__temperature of each day__ 

[[24 29 32 34 18 21 26 18 34 31 35 33 18 29 20 19 34 29 19 19 20 29 24 32]
 [28 35 23 19 39 30 20 39 36 27 21 34 36 24 37 22 31 36 37 31 20 26 19 36]
 [22 34 19 37 19 21 34 32 27 22 34 37 38 24 27 32 33 37 25 38 34 20 35 24]
 [30 38 25 24 35 24 27 30 26 22 33 22 28 39 19 28 22 31 19 22 25 29 19 29]
 [27 33 38 30 24 38 26 18 21 34 30 26 38 27 34 29 34 37 39 19 24 26 19 23]
 [27 25 20 29 22 27 38 36 19 32 34 27 27 35 22 29 24 27 23 32 22 30 22 20]
 [37 37 24 21 25 32 39 26 25 37 32 26 25 33 20 38 35 36 30 26 25 18 33 20]]

average temp in day  1  :  26.125
max temp in day  1  :  35
min temp in day  1  :  18
average temp in day  2  :  29.416666666666668
max temp in day  2  :  39
min temp in day  2  :  19
average temp in day  3  :  29.375
max temp in day  3  :  38
min temp in day  3  :  19
average temp in day  4  :  26.916666666666668
max temp in day  4  :  39
min temp in day  4  :  19
average temp in day  5  :  28.91