In [1]:
import numpy as np

In [2]:
temp=np.random.randint(18,40,168)
re_shape=np.reshape(temp,(7,24))


In [3]:
avg_day=np.mean(re_shape,axis=1)
max_day=np.max(re_shape,axis=1)
min_day=np.min(re_shape,axis=1)
hot_hour=temp[temp>35]
average=np.average(temp)
min=np.min(temp)
max=np.max(temp)


In [4]:

print("------weekly temperature analyzer------ \n")
print()
print("__temperature of each day__ \n")
print(re_shape)
print()
for i in range(7):
   print("average temp in day ",i+1," : ",avg_day[i])
   print("max temp in day ",i+1," : ",max_day[i])
   print("min temp in day ",i+1," : ",min_day[i])
print()
print("hot hour : ",hot_hour)
print()
print("average temp in week : ",average)
print()
print("min temp in week : ",min)
print()
print("max temp in week  : ",max)


------weekly temperature analyzer------ 


__temperature of each day__ 

[[25 20 20 25 27 18 32 37 37 39 33 26 30 19 24 38 32 38 26 29 32 38 31 18]
 [18 28 31 31 33 26 24 32 21 34 36 18 23 36 35 31 31 32 33 32 31 34 23 37]
 [29 34 32 35 32 35 36 29 20 26 39 35 24 29 20 21 30 36 20 36 39 26 32 24]
 [26 22 32 19 31 34 28 38 20 27 32 32 19 39 36 27 19 31 31 19 27 28 25 24]
 [31 34 39 33 25 26 19 24 38 39 31 28 38 26 36 39 19 24 31 28 19 39 32 32]
 [29 22 24 23 18 28 23 39 20 19 38 29 36 26 37 28 28 37 25 24 26 24 36 26]
 [26 22 32 37 19 38 35 38 31 36 35 22 37 24 34 28 19 32 20 23 35 37 35 25]]

average temp in day  1  :  28.916666666666668
max temp in day  1  :  39
min temp in day  1  :  18
average temp in day  2  :  29.583333333333332
max temp in day  2  :  37
min temp in day  2  :  18
average temp in day  3  :  29.958333333333332
max temp in day  3  :  39
min temp in day  3  :  20
average temp in day  4  :  27.75
max temp in day  4  :  39
min temp in day  4  :  19
average temp in day  